kaikei/urls.py
from django.urls import path
from . import views

app_name = 'kaikei'

urlpatterns = [
    path('', views.index, name='index'),
    #path('top/', views.top, name='top'),
    path('top/', views.waitingcustomer_list, name='top'),
    # path('reception/', views.reception, name='customer_search'),
    path('reception/', views.CustomerList.as_view(), name='customer_list'),
    path('detail/<int:pk>/', views.CustomerDetail.as_view(), name='customer_detail'),
    path('update/<int:pk>/', views.CustomerUpdate.as_view(), name='customer_update'),
    #path('login/', views.login, name='login'),
    #path('login/choice/', views.ChoiceCreate.as_view(), name='choice_create'),
    path('choice/', views.ChoiceCreate.as_view(), name='choice_create'),
    #path('login/accounts/', views.accounts, name='accounts'),
    path('accounts/', views.accounts, name='accounts'),
    path('create/', views.CustomerCreate.as_view(), name='customer_create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('kaikei/', include('kaikei.urls')),
    path('', include('kaikei.urls')),
    #path('kaikei/', include('django.contrib.auth.urls')),
    path('', include('django.contrib.auth.urls')),
]

kaikei/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    age = models.IntegerField(null=True)

class Clinic(models.Model):
    name = models.CharField('名前', max_length=255)

class Branch(models.Model):
    name = models.CharField('支店', max_length=255)
    clinic = models.ForeignKey(Clinic, verbose_name='所属医院', blank=False, on_delete=models.PROTECT)
   
class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    name = models.CharField('名前', max_length=255)
    is_waiting = models.BooleanField('来院中', default=False)

    def __str__(self):
        return 'No.{}: {}'.format(self.customer_id, self.name)    

"""
class WaitingCustomer(models.Model):
   customer = models.ForeignKey(Customer, verbose_name='顧客', blank=False, on_delete=models.PROTECT, limit_choices_to={'is_waiting': True}) 
"""

class Hoken(models.Model):
    name = models.CharField('名前', max_length=255)
    price = models.IntegerField('価格')

    def __str__(self):
        return '{}: {}円'.format(self.name, self.price)

class Jiseki(models.Model):
    name = models.CharField('名前', max_length=255)
    price = models.IntegerField('価格')

    def __str__(self):
        return '{}: {}円'.format(self.name, self.price)

class Buturyou(models.Model):
    name = models.CharField('名前', max_length=255)
    price = models.IntegerField('価格')

    def __str__(self):
        return '{}: {}円'.format(self.name, self.price)

class Shouhin(models.Model):
    name = models.CharField('名前', max_length=255)
    price = models.IntegerField('価格')

    def __str__(self):
        return '{}: {}円'.format(self.name, self.price)

class Product(models.Model):
    hoken = models.ForeignKey(Hoken, verbose_name='保険', blank=False, on_delete=models.PROTECT)
    jiseki = models.ForeignKey(Jiseki, verbose_name='自責', blank=False, on_delete=models.PROTECT)
    buturyou = models.ForeignKey(Buturyou, verbose_name='物療', blank=False, on_delete=models.PROTECT)
    shouhin = models.ForeignKey(Shouhin, verbose_name='商品', blank=False, on_delete=models.PROTECT)

class Payment(models.Model):
    name = models.CharField('支払方法', max_length=255)

    def __str__(self):
        return self.name

class Staff(models.Model):
    staff_id = models.AutoField(primary_key=True)
    name = models.CharField('名前', max_length=255)

    def __str__(self):
        return 'No.{}: {}'.format(self.staff_id, self.name)

class Choice(models.Model):
    hoken = models.ForeignKey(Hoken, verbose_name='保険', blank=False, on_delete=models.PROTECT)
    hoken_number = models.IntegerField('個数（保険）',default=1, validators=[MinValueValidator(0)])
    hoken_total_score = models.IntegerField('小計（保険）')
    jiseki = models.ForeignKey(Jiseki, verbose_name='自責', blank=False, on_delete=models.PROTECT)
    jiseki_number = models.IntegerField('個数（自責）',default=1, validators=[MinValueValidator(0)])
    jiseki_total_score = models.IntegerField('小計（自責）')
    buturyou = models.ForeignKey(Buturyou, verbose_name='物療', blank=False, on_delete=models.PROTECT)
    buturyou_number = models.IntegerField('個数（物療）',default=1, validators=[MinValueValidator(0)])
    buturyou_total_score = models.IntegerField('小計（物療）')
    shouhin = models.ForeignKey(Shouhin, verbose_name='商品', blank=False, on_delete=models.PROTECT)
    shouhin_number = models.IntegerField('個数（商品）',default=1, validators=[MinValueValidator(0)])
    shouhin_total_score = models.IntegerField('小計（商品）')
    total_score = models.IntegerField('合計')
    customer = models.ForeignKey(Customer, verbose_name='顧客', blank=False, on_delete=models.PROTECT, limit_choices_to={'is_waiting': True})
    created_at = models.DateTimeField('支払日', default=timezone.now)
    payment = models.ForeignKey(Payment, verbose_name='支払方法', blank=False, on_delete=models.PROTECT)
    staff = models.ForeignKey(Staff, verbose_name='担当者', blank=False, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        self.hoken_total_score = self.hoken.price * self.hoken_number
        self.jiseki_total_score = self.jiseki.price * self.jiseki_number
        self.buturyou_total_score = self.hoken.price * self.buturyou_number
        self.shouhin_total_score = self.hoken.price * self.shouhin_number
        self.total_score = self.hoken_total_score + self.jiseki_total_score + self.buturyou_total_score + self.shouhin_total_score
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}:{}さん({})'.format(self.created_at, self.customer.name, self.id)

kaikei/forms.py
from django import forms
from .models import Customer, Choice

class CustomerCreateForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        exclude = (
            'is_waiting',
        )

class CustomerUpdateForm(forms.ModelForm):

    class Meta:
        model = Customer
        exclude = {
            'customer_id',
            'name',
        }

class ChoiceCreateForm(forms.ModelForm):

    class Meta:
        model = Choice
        exclude = (
            'hoken_total_score',
            'jiseki_total_score',
            'buturyou_total_score',
            'shouhin_total_score',
            'total_score',
        )

class CustomerSearchForm(forms.Form):
    customer_id = forms.IntegerField(label='顧客ID', required=True, widget=forms.TextInput(attrs={'class': 'input'}))

kaikei/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q
from .forms import CustomerCreateForm, CustomerUpdateForm, ChoiceCreateForm, CustomerSearchForm
from . import forms
from .models import Customer, Choice

# Create your views here.
def index(request):
    return render(request, 'kaikei/index.html')

"""
class Text(LoginRequiredMixin, generic.TemplateView):
    template_name = 'kaikei/test.html'
"""

@login_required
def top(request):
    return render(request, 'kaikei/top.html')

"""
# def reception(request):
    return render(request, 'kaikei/reception.html')
"""

class CustomerList(generic.ListView):
    model = Customer

    def get_queryset(self):
        queryset = super().get_queryset()
        form = CustomerSearchForm(self.request.GET or None)
        if form.is_valid():
            customer_id = form.cleaned_data.get('customer_id')
            if customer_id:
                queryset = queryset.filter(Q(customer_id__icontains=customer_id))
        return queryset

"""
class IndexView(LoginRequiredMixin, generic.ListView):
    paginate_by = 5
    template_name = 'search/index.html'
    model = Post
    def post(self, request, *args, **kwargs):
        form_value = [
            self.request.POST.get('title', None),
            self.request.POST.get('text', None),
        ]
        request.session['form_value'] = form_value
        # 検索時にページネーションに関連したエラーを防ぐ
        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()
        return self.get(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # sessionに値がある場合、その値をセットする。（ページングしてもform値が変わらないように）
        title = ''
        text = ''
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
            text = form_value[1]
        default_data = {'title': title,  # タイトル
                        'text': text,  # 内容
                        }
        test_form = SearchForm(initial=default_data) # 検索フォーム
        context['test_form'] = test_form
        return context
    def get_queryset(self):
        # sessionに値がある場合、その値でクエリ発行する。
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
            text = form_value[1]
            # 検索条件
            condition_title = Q()
            condition_text = Q()
            if len(title) != 0 and title[0]:
                condition_title = Q(title__icontains=title)
            if len(text) != 0 and text[0]:
                condition_text = Q(text__contains=text)
            return Post.objects.select_related().filter(condition_title & condition_text)
        else:
            # 何も返さない
            return Post.objects.none()
"""

"""
class WaitingCustomerList(generic.ListView):
    queryset = Customer.objects.filter(is_waiting=True)
"""

def waitingcustomer_list(request):
    context = {
        'waitingcustomer_list': Customer.objects.filter(is_waiting=True),
    }
    return render(request, 'kaikei/waitingcustomer_list.html', context)

class CustomerDetail(generic.DetailView):
    model = Customer

class CustomerUpdate(generic.UpdateView):
    model = Customer
    form_class = CustomerUpdateForm
    success_url = reverse_lazy('kaikei:top')

#def login(request):
    #return render(request, 'kaikei/login.html')

"""
#def choice_create(request):
    form = ChoiceCreateForm(request.POST or None)
    customer = Choice.objects.filter(customer__is_waiting=True)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('kaikei:accounts')
    
    context = {
        'form': form
    }
    return render(request, 'kaikei/choice_form.html', context)
"""

class ChoiceCreate(generic.CreateView):
    model = Choice
    # customer = Choice.objects.filter(customer__is_waiting=True)
    form_class = ChoiceCreateForm
    success_url = reverse_lazy('kaikei:accounts')

    # def get_queryset(self):
    #    return Choice.objects.filter(customer__is_waiting=True)

def accounts(request):
    choice = Choice.objects.last()
    context = {
        'choice': choice
    }
    #return render(request, 'kaikei/login/accounts.html', context)
    return render(request, 'kaikei/accounts.html', context)

class CustomerCreate(generic.CreateView):
    model = Customer
    form_class = CustomerCreateForm
    success_url = reverse_lazy('kaikei:top')

kaikei/templates/kaikei/accounts.html
{% extends 'kaikei/base.html' %}
{% block content %}
    <p>保険  小計：{{ choice.hoken_total_score }}円</p>
    <p>自責  小計：{{ choice.jiseki_total_score }}円</p>
    <p>物療  小計：{{ choice.buturyou_total_score }}円</p>
    <p>商品  小計：{{ choice.shouhin_total_score }}円</p>
    <p>　　  合計：{{ choice.total_score }}円</p>
    <form action="{% url 'kaikei:top' %}" method="GET">
        <button type="">トップへ</button>
    </form>
{% endblock %}

kaikei/templates/kaikei/base.html
{% load static %}
<!doctype html>
{% load kaikei %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>kaikei</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

kaikei/templates/kaikei/choice_form.html
{% extends 'kaikei/base.html' %}
{% block content %}
<!--
    <form action="" method="POST">
        {% if form.errors %}
        <div class="errorlist">
            {% for errors in form.errors.values %}
                {% for error in errors %}
                    {{ error }}<br>
                {% endfor %}
            {% endfor %}
        </div>
        {% endif %}

        <div class="field">
            <label>商品</label>
            <select>
                <option>--------</option>
                {% for x in form.field.hoken %}
                <option>{{ x }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label>個数</label>
            <input type="number">
        </div>

        {% csrf_token %}
        <button type="submit">会計画面へ</button>
    </form>
-->

    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <span class="helptext">{{ field.help_text }}</span>
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <p>送信後、is_waiting==Falseにする</p>
        {% csrf_token %}
        <button type="submit">会計画面へ</button>
    </form>

{% endblock %}

kaikei/templates/kaikei/customer_detail.html
{% extends 'kaikei/base.html' %}
{% block content %}
    <p>名前: {{ customer.name }} - 来院中: {{ customer.is_waiting }}</p>
    <a href="{% url 'kaikei:customer_update' customer.pk %}">更新</a>
{% endblock %}

kaikei/templates/kaikei/customer_form.html
{% extends 'kaikei/base.html' %}
{% block content %}
    <p>※他に必要な属性があれば作成</p>
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">登録</button>
    </form>
{% endblock %}

kaikei/templates/kaikei/customer_list.html
{% extends 'kaikei/base.html' %}
{% load kaikei %}
{% block content %}
    <aside class="column is-4 is-offset-1">
        {% create_search_form request %}
    </aside>
    <div>
        {% for customer in customer_list %}
            <option>ID: {{ customer.customer_id }} 名前: {{ customer.name }}</option>
            <p><a href="{% url 'kaikei:customer_detail' customer.customer_id %}">受付</a></p> 
        {% endfor %}  
    </div>
    {% if queryset %}
        {% for customer in queryset %}
            <p><a href="{% url 'kaikei:customer_detail' customer.customer_id %}">受付</a></p> 
        {% endfor %}
    {% endif %}
    <a href="{% url 'kaikei:top' %}">トップへ</a>
{% endblock %}

kaikei/templates/kaikei/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>トップ画面</title>
</head>
<body>
    
    <h1>トップ画面</h1>

    {% if user.is_authenticated %}
    <p><a href="{% url 'logout' %}">ログアウト</a></p>
    {% else %}
    <p><a href="{% url 'login' %}">ログイン</a></p>
    {% endif %}

</body>
</html>

kaikei/templates/kaikei/new_search_form.html
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 py-2">
            <nav aria-label="ページ送り">
                <div class="text-center">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(現位置)</span></a>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>

kaikei/templates/kaikei/pagination.html
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 py-2">
            <nav aria-label="ページ送り">
                <div class="text-center">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(現位置)</span></a>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>

kaikei/templates/kaikei/search_form.html
<p class="menu-label">検索フォーム</p>
<form action="{% url 'kaikei:customer_list' %}" method="GET">
    <div class="field">
        <div class="control">
            {{ form.customer_id }}
        </div>
    </div>

    <button class="button is-primary" type="submit">検索</button>
</form>

kaikei/templates/kaikei/top.html
{% extends 'kaikei/base.html' %}
{% block content %}
<html>{% include './waitingcustomer_list.html' %}</html>
    <p>こんにちは{{ user.username }}さん</p>
    <a href="{% url 'kaikei:customer_list' %}">受付</a><br>
    <a href="{% url 'kaikei:choice_create' %}">会計</a><br>
    <a href="{% url 'kaikei:customer_create' %}">新規登録</a><br>
    <a href="http://127.0.0.1:8000/admin/">管理ページ</a><br>
    <p><a href="{% url 'logout' %}">ログアウト</a></p>
{% endblock %}

kaikei/templates/kaikei/waitingcustomer_list.html
{% extends 'kaikei/base.html' %}
{% block content %}
<p>こんにちは{{ user.username }}さん</p>
<a href="{% url 'kaikei:customer_list' %}">受付</a><br>
<a href="{% url 'kaikei:choice_create' %}">会計</a><br>
<a href="{% url 'kaikei:customer_create' %}">新規登録</a><br>
<a href="http://127.0.0.1:8000/admin/">管理ページ</a><br>
<p><a href="{% url 'logout' %}">ログアウト</a></p>
<p>会計待ち</p>
    {% for customer in waitingcustomer_list %}
        {{ customer.name }}<br>
    {% endfor %}
{% endblock %}